#############################
# WINDOW RULES
#############################

windowrule = match:class org.telegram.desktop, float on, size 370 500 
windowrule = float on, match:class discord, size 1150 650
windowrule = float on, match:class net.lutris.Lutris, size 1000 900, workspace 1 silent
windowrule = match:class steam, float on, workspace 1 silent
windowrule = match:class firefox, match:title (.*Sign In - Google Accounts.*), float on
windowrule = match:class firefox, match:title (.*Bitwarden.*), float on
windowrule = match:title ^Picture-in-Picture$, float on

windowrule = match:class ^spotify$, workspace 3 silent
windowrule = match:class ^tidal-hifi$, workspace 3 silent

windowrule = opacity 0.8 override 0.75 override 1.0 override, match:class firefox
windowrule = opacity 1.0 override, match:title (.*YouTube.*)
windowrule = opacity 1.0 override, match:title (.*Max.*)
windowrule = opacity 1.0 override, match:title (.*Prime Video.*)
windowrule = opacity 1.0 override, match:title (.*Netflix.*)
windowrule = opacity 1.0 override, match:title (.*Disney.*)
windowrule = opacity 1.0 override, match:title (.*Twitch.*)
windowrule = opacity 1.0 override, match:title (.*Kick.*)
windowrule = opacity 1.0 override, size 750 422, match:class firefox, match:title Picture-in-Picture
windowrule = opacity 1.0 override, match:pin true

windowrule = idle_inhibit fullscreen, match:class .*
windowrule = suppress_event maximize, match:class .*
windowrule = opacity 0.0 override, match:class ^(xwaylandvideobridge)$
windowrule = no_anim on, match:class ^(xwaylandvideobridge)$
windowrule = no_initial_focus on, match:class ^(xwaylandvideobridge)$
windowrule = max_size 1 1, match:class ^(xwaylandvideobridge)$
windowrule = no_blur on, match:class ^(xwaylandvideobridge)$
